version: '3.8'

services:
  db:
    image: mongo:latest
    container_name: blog-db
    ports:
      - "27017:27017"
    volumes:
      - ./data_moved/db:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ping: 1})"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    restart: always

  api:
    build: .
    container_name: blog-api
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://db:27017/my_blog_db
    depends_on:
      db:
        condition: service_healthy
    restart: always
